---
driver:
  name: docker_cli

transport:
  name: docker_cli

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ruby_for_busser: false
  requirements_path: <%= ENV['REQUIREMENTS_PATH'] || "test/requirements.yml" %>
  ansible_cfg_path: ansible.cfg
  ansible_verbose: false
  ansible_verbosity: :warn
  ansible_version: latest
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  playbook: <%= ENV['PLAYBOOK'] || "test/integration/default/default.yml" %>
  env_vars:
    LOGSTASH_SERVER: <%= ENV['LOGSTASH_SERVER'] || "172.17.0.3" %>
  ignore_paths_from_root:
    - .bundle
    - .kitchen
    - .git
    - tests
    - vendor
#  idempotency_test: true

platforms:
  - name: centos-6
    driver_config:
      platform: centos
      image: c6h12o6-centos6
      privileged: true
      command: /sbin/init
      network: host
      skip_preparation: true

  - name: centos-7
    driver_config:
      platform: centos
      image: c6h12o6-centos7
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /usr/lib/systemd/systemd
      network: host
      skip_preparation: true

  - name: debian-7
    driver_config:
      platform: debian
      image: c6h12o6-debian7
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      network: host
      skip_preparation: true

  - name: debian-8
    driver_config:
      platform: debian
      image: c6h12o6-debian8
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      network: host
      skip_preparation: true

  - name: debian-9
    driver_config:
      platform: debian
      image: c6h12o6-debian9
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      network: host
      skip_preparation: true

  - name: ubuntu-12.04
    driver_config:
      platform: ubuntu
      image: c6h12o6-ubuntu1204
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      network: host
      skip_preparation: true

  - name: ubuntu-14.04
    driver_config:
      platform: ubuntu
      image: c6h12o6-ubuntu1404
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      network: host
      skip_preparation: true

  - name: ubuntu-16.04
    driver_config:
      platform: ubuntu
      image: c6h12o6-ubuntu1604
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      stop_signal: SIGRTMIN+3
      tmpfs:
        - /run
        - /run/lock
      network: host
      skip_preparation: true

  - name: fedora-24
    driver_config:
      platform: rhel
      image: c6h12o6-fedora24
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /usr/lib/systemd/systemd
      network: host
      skip_preparation: true

  - name: fedora-25
    driver_config:
      platform: rhel
      image: c6h12o6-fedora25
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /usr/lib/systemd/systemd
      network: host
      skip_preparation: true

suites:
  - name: default
...
