FROM bdellegrazie/docker-fedora25-ansible:latest
RUN sudo dnf install -y python-pip
RUN sudo pip install --upgrade --ignore-installed --no-cache-dir pip
RUN sudo pip install setuptools==33.1.1 --ignore-installed --no-cache-dir
RUN sudo pip install python-logstash --ignore-installed --no-cache-dir
